tags:
- name: health
  description: health check API

paths:
# [GET] health check
  /healthcheck:
    get:
      tags:
      - health
      summary: health check endpoint
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

schemes:
 - https
 - http
