tags:
- name: health
  description: health check API
        
paths:
  /healthcheck:
    get:
      summary: health check endpoint
      tags:
        - health
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /information/blocks:
    get:
      summary: Get block chain related information that processed in the service
      tags:
        - home
      responses:
        '200':
          description: Last 50 blocks and the latest mined block, as well as the last committed block in subnet and parent chain
          content: 
            'application/json':
              schema: 
                type: object
                properties:
                  blocks:
                    description: A list of existing master nodes. Sorted by block number
                    type: array
                    items:
                      $ref: '#/definitions/Block'
                  latestMinedBlock:
                    description: The block that was most recently mined in the subnet. regardless its confirmation status
                    properties:
                      hash:
                        type: string
                      number:
                        type: number
                  latestCommittedBlock:
                    description: The block that was most recently confirm to be committed in the subnet. (Ignoring its confirmation status from parent chain)
                    properties:
                      hash:
                        type: string
                      number:
                        type: number
                    
        '400':
          description: 'Bad Request'
        '409':
          description: 'Conflict'
        '500':
          description: 'Server Error'
  /information/masterNodes:
    get:
      summary: Get master nodes information such as committed size and their status
      tags:
        - home
      responses:
        '200':
          description: Master node information
          content: 
            'application/json':
              schema: 
                type: object
                properties:
                  summary:
                    description: Summary information about all the nodes.
                    type: object
                    properties:
                      committed:
                        type: integer
                      activeNode:
                        type: integer
                      standByNode:
                        type: integer
                    required:
                      - committed
                      - activeNode
                  nodes:
                    description: A list of existing master nodes. Sorted by nodeId
                    type: array
                    items:
                      $ref: '#/definitions/MasterNode'
        '400':
          description: 'Bad Request'
        '409':
          description: 'Conflict'
        '500':
          description: 'Server Error'
  /information/relayer:
    get:
      summary: Get the relayer related system information such as admin account address and balance, relayer status etc.
      tags:
        - home
      responses:
        '200':
          content: 
            'application/json':
              schema: 
                type: object
                properties:
                  account:
                    description: The admin/super account information
                    type: object
                    properties:
                      balance:
                        description: The super/admin account remaining balance in XDC
                        type: string
                      walletAddress:
                        description: The wallet address of the account
                        type: string
                    required:
                      - walletAddress
                      - balance
                  backlog:
                    description: The current gap between audited block in smartcontract (parent chain) and latest minded block in subnet 
                    type: integer
                  contractAddress:
                    type: string
                  health:
                    type: object
                    properties:
                      status:
                        description: An enum value to indicate the current relayer status.
                        type: string
                        enum: [UP, DOWN]
                      details:
                        description: A short description about the current running status when there is an issue. E.g System is running but very low
                        type: string
                required:
                  - account
                  - contractAddress
                  - backlog
                  - health
        '400':
          description: 'Bad Request'
        '409':
          description: 'Conflict'
        '500':
          description: 'Server Error'
  /information/network:
    get:
      summary: Get the subnet network information, such as block mining time, tx throughput etc
      tags:
        - home
      responses:
        '200':
          content: 
            'application/json':
              schema: 
                type: object
                properties:
                  subnet:
                    type: object
                    properties:
                      block:
                        description: block metadata, such as mining frequency
                        type: object
                        properties:
                          averageBlockTime:
                            description: The block mining time per X second.
                            type: integer
                          txThroughput:
                            description: The subnet transaction throughput, we only keep track of the last 10 txs and take average per second.
                            type: integer
                    required:
                      - block
                  parentChain:
                    type: object
                    properties:
                      targetChain:
                        description: A string value which is used to identify the target parent chain. It can be a URL, IP address or a name.
                        type: string
                    required:
                      - targetChain
                  health:
                    type: object
                    properties:
                      status:
                        description: An enum value to indicate the current relayer status.
                        type: string
                        enum: [UP, DOWN]
                      details:
                        description: A short description about the current running status when there is an issue. E.g System is running but very low
                        type: string
                required:
                  - subnet
                  - parentChain
                  - health
        '400':
          description: 'Bad Request'
        '500':
          description: 'Server Error'
                  
  /confirmation:
    get:
      summary: This endpoint is used to get confirmation information for a particular subnet block height, block hash or transaction hash.
      tags:
        - confirmation
      parameters:
        name: input
        in: path
        description: The block height or hash or transaction hash
        required: true
        type: string
      responses:
        '200':
          content: 
            'application/json':
              schema: 
                type: object
                properties:
                  inputType:
                    type: string
                    enum: [BLOCK_HEIGHT, BLOCK_HASH, TRANSACTION_HASH, INVALID]
                  subnet:
                    type: object
                    properties:
                      isConfirmed:
                        type: boolean
                      blockHeight:
                        type: integer
                      blockHash:
                        type: string
                    required:
                      - isConfirmed
                      - blockHeight
                      - blockHash
                  parentChain:
                    type: object
                    properties:
                      isConfirmed:
                        type: boolean
                      blockHeight:
                        type: integer
                      blockHash:
                        type: string
                      proposer:
                        type: string
                    required:
                      - isConfirmed
                      - blockHeight
                      - blockHash
                  transaction:
                    type: object
                    properties:
                      isConfirmed:
                        type: boolean
                      from:
                        type: string
                      to:
                        type: string
                      timestamp:
                        type: string
                      gas:
                        type: string
                required:
                  - inputType
                  - subnet
                  - parentChain
        '400':
          description: 'Bad Request'
        '500':
          description: 'Server Error'
                      
# definitions
definitions:
  MasterNode:
    type: object
    properties:
        address:
          description: The master node xdc address in subnet
          type: string
        role:
          type: string
          enum: [STANDBY, MINER, PENALTY]
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
        currentHeight:
          type: integer
    required:
      - address
      - role
  Block:
    type: object
    properties:
        hash:
          description: The subnet block hash
          type: string
        number:
          description: The subnet block number
          type: number
        round:
          description: The subnet block round number
          type: number
        parentHash:
          description: The subnet block's parentHash
          type: string
        committedInSubnet:
          description: This boolean value is to indicate whether this block has been confirmed in the subnet itself
          type: boolean
        committedInParentChain:
          description: This boolean value is to indicate whether this block has been confirmed in the parent chain smart contract
          type: boolean
    required:
      - hash
      - number
      - committedInParentChain
      - committedInSubnet
        
schemes:
 - https
 - http
