# NodeJS Version 16
FROM node:16.18-alpine

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN apk add g++ make python3
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV production
EXPOSE 3000
EXPOSE 443

# Cmd script
CMD ["npm", "run", "start"]
