name: PR tests

on:
  pull_request:
    branches:    
      - master
  
jobs:
  test_on_pr_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: cd backend && npm install
    - name: Run build
      run: cd backend && npm run build # Double check we can build
    # TODO: Tests to be added
    # - name: Unit tests
    #   run: npm run test

  test_on_pr_frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: cd frontend && yarn
      env:
        NODE_ENV: production

    - name: Test build 
      run: cd frontend && yarn run build
      env:
        NODE_ENV: production

    - name: Test serve 
      run: cd frontend && yarn global add serve
      env:
        NODE_ENV: production
